---
title: "info201final"
output: html_document
date: "2023-12-07"
---

# Group 3: INFO201 Final Project 

## Introduction

#### As students attending the University of Washington, we feel incredibly lucky to have an immense wealth of resources at our fingertips. This was a common sentiment for the team, as opportunities for learning and professional development are widely available to us. However, upon reflecting on our respective experiences, we began to wonder about the cycle that we are a part of. The United States boasts about its academic programs, which largely benefit certain demographics above others. Part of the ideology around academia in this country is that it helps further a capitalistic, individualistic and efficiently earning society. How does the education system of a country relate to its average income per capita, and is this concept paradoxical in nature? 

<br>

#### To begin the investigation, we read various articles. While they were mostly about paradigms within the United States, there were some theories that were related to our larger discussion. According to Ann Owens, a professor of Sociology at University of Southern California, “When families are highly segregated by income between school districts, resources that contribute to students’ academic successes, such as school funding, teacher quality, parents’ social capital, and students’ peer characteristics, are more unequally distributed” (Owens, 2018). While this source is referencing disparities between local districts, the overall idea may be applied to a worldwide analysis. Another study from 1998 found that nationally, kindergarteners from high-income families were found by teachers to be more than half of a standard deviation ahead of those from low-income families in terms of math or literacy rates (Duncan & Murnane, 2011).The internal processes of the United States, while acting as a testament for how income might impact education nationally, may embody more widespread, global inequalities. These are important because educating ourselves about how income disparities can translate into unequal access to educational opportunities may help us understand how to promote a more equitable society. This helped us determine our target audience, which is people in academia or college students that wish to learn more about the issues, and policy makers that can have an impact on allocation of resources.

<br>

#### In our research, we navigated through a myriad of intersecting societal patterns and factors. We aimed to identify correlations between a country’s average income and its state of education, and make relevant assertions regarding the impact of monetary resources on academic presence and success. This information can be used to draw conclusions about the global economy and international dynamics. One of the questions we hope to address is: is there an association between average income and education completion rate? Does this trend (if any) persist with the rate of out-of-school primary students? In terms of income-specific variables, our data examines the unemployment rate per country (in correspondence with its education factors), and the categorical grouping of countries by GDP per capita (low, mid, and high). Finally, we wanted to understand why these statistics might differ depending on gender, and how this phenomenon may represent certain widespread social norms. 

<br>

#### We aspired to find and define a narrative that interlinks these factors, and to investigate their circular nature (how they might propel and influence each other). Our goal was to prove that income and educational success influence each other, and that a country with a lower average income per capita will have lower completion, enrollment, and employment rates. We also intend to visit underlying gender stereotypes in various education systems. Ideally, this will help expand the reader’s knowledge of this potentially unjust relationship, and provide insight into how to start addressing potential issues that the data brings to light. 

<br>

## Data

#### We wanted to make sure that our datasets were widely accessible, so we decided to use Kaggle, which is an online community of data scientists and users that upload code and datasets that are free for viewers to download (provided that they make an account on the website). The datasets that we selected are created by different users. 

<br>

#### The dataset describing GDP was created by Raj Kumar Pandey, a data analyst at Bses RajDhani Power LTD, and the dataset depicting world education data was created by Nidula Elgiriyewithana, a data scientist at Dialog Axiata PLC. Both datasets are public domain/publically available. The GDP (in USD) Per Capita Income by Country dataset by Pandey is a list of countries by GDP per capita. The column that we chose to examine was the IMF estimate, which is the estimate of GDP per capita per country by the International Monetary fund. While there were other columns with different estimates and economic growth factors, this one seemed the most straightforward. There were 224 unique values for countries, and the population taken into account was the population of a country that was calculated to have a certain GDP per capita. While the GDP may have been determined from a sample of people from each region, it is not noted in the description of the dataset. The World Educational Data table by Elgiriyewithana is supposed to represent a view of education on a global scale, with varying factors such as out-of-school rate, enrollment and completion rates, employment rate, and literacy rate per country. We decided to stray away from literacy rate and such, due to the subjectivity of how literacy is defined. The countries are also listed by latitude and longitude. This one, on the contrary to the first dataset, had only 202 countries listed, which was a disparity that we ran into right away. The population taken into account was most likely the general population of each country, with the sample size being those who were used in the study to determine certain rates of academic presence and success. 

<br>

#### Right away, we ran into some problems when merging these datasets. Primarily, the difference in country count led us to have to remove the countries that were not contributing to our data analysis due to their absence in the World Education resource. Additionally, many countries such as the United States and United Kingdom were not accounted for in most variables of the World Education resource, which removed a lot of the larger values for GDP and completion rate from the equation. Because of this, we had to adjust our bins for low, mid, and high values of GDP to make up for the fact that many of the countries we did have data for education-wise had an extremely low GDP. We had to adjust the starting point of our axes, and remove zeros from our plots due to their presence representing a lack of data. 

<br>

#### In our final dataset, FINALgdp_global_education, a row specifies a specific country, along with their GDP and educational factors. 

<br>

#### Our dataset contains 179 observations.

<br>

#### In our dataset, we have the variables: Completion_Rate_Primary_Female, Completion_Rate_Primary_Male, Country.Territory, Education_Gap, IMF, OOSR_Primary_Age_Female, OOSR_Primary_Age_Male, Rank_of_GDP_per_Capita, Unemployment_Rate. 


#### The only variables we coded and added ourselves were Education_Gap and Rank_of_GDP_per_Capita. For Education_Gap,  we calculated the absolute value of the completion rate of males vs females, so it just shows the percentage difference of males that complete school vs females. For Rank_of_GDP_per_Capita, we divided countries into different bins according to their GDP per capita. GDP per capita values between 0 and 1000 are categorized as "Low." Values between 1000 and 5000 are categorized as "Mid." Values between 5001 and 25000 are categorized as "High." Anything else that doesn't meet these conditions is marked as NA_character_, which means missing or not applicable in this context. 

<br>

#### Number of Missing (na and values of 0) in each variable:
#### Country.Territory: 0
#### IMF: 0
#### Completion_Rate_Primary_Male: 81
#### Completion_Rate_Primary_Female: 81
#### Unemployment_Rate: 14
#### OOSR_Primary_Age_Male: 69
#### OOSR_Primary_Age_Female: 74
#### Rank_of_GDP_per_Capita: 39
#### Education_Gap: 96

<br>

## Methods

#### For data processing, we merged the datasets based on the common identifier, country name, which was “Country.Territory” in the GDP dataset and “Countries.and.areas” in the Global Education dataset. 

<br>

#### To gauge a country's economic performance and standard of living, we are using the IMF (GDP per Capita Estimated by the International Monetary Fund) from the GDP dataset. This variable allows for the examination of the economic dimension in relation to education indicators.

<br>

#### From the Global Education dataset, we included the Primary Completion Rate in Males and Females because they serve as an indicator of the education system's effectiveness in a country and reflect the percentage of students who successfully complete primary education. From the Global Education dataset, we also included the Out-of-School Rate (OOSR) in Males and Females, which represents the percentage of children who are not enrolled in primary education at the appropriate age and is also used to provide insights into the accessibility and inclusivity of the education system. By using these variables categorized by gender, we wanted to also identify gender-specific trends or challenges in achieving primary education. 

<br>

#### We are also using the unemployment rate variable from the Global Education dataset, which measures the percentage of the labor force that is unemployed and actively seeking employment, serving as a key economic indicator that reflects the overall health of a country's economy and could indicate economic and educational challenges.

<br>

#### We used left_join() for data merging because it looks for matching columns between the two data frames (country names), and then returns a new data frame that is the first data frame with extra columns from the second data frame appended on.  This choice was made considering that the GDP dataset might have more comprehensive coverage, and we wanted to retain all entries from it. For variable selection, we selected variables related to primary education completion rates for males and females, where we removed missing values (“na.omit”) to ensure that our analysis is based on complete and valid data. 

<br>

#### For our additional categorical variable, we categorized countries into different income classes based on their GDP per capita (IMF), creating the variable “Rank_of_GDP_per_Capita”. Countries are categorized into "Low," "Mid," or "High" based on ranges of GDP per capita, and the “mutate” function was used to add this new variable to the dataset. The “TRUE ~ NA_character_ line” serves as a catch-all for cases that don't meet the specified conditions. This categorical variable allows us to explore how education indicators vary across different income classes, providing a more nuanced view than considering GDP per capita as a continuous variable.

<br>

#### For our additional numerical variable, we created “education_gap”, which represents the absolute difference between the completion rates of males and females and allows for a way to quantify the gender gap in primary education completion rates. Taking the absolute value ensures that the gap is represented without consideration of the direction (whether males or females have a higher completion rate), and the “mutate” function was used to add this new variable to the dataset.

<br>

#### We removed missing values and zero values from the dataset (“na.omit(FINALgdp_global_education)” and FINALgdp_global_education[FINALgdp_global_education$IMF != 0, ]) to prevent distortion in the analysis as zero values may represent missing or inaccurate data. 

<br>

#### We created a world map to visually represent the distribution of countries based on their GDP per capita ranks. Each country was color-coded into three categories: Low, Mid, and High, representing different ranks of GDP per capita. This map provides a global perspective, allowing us to observe geographical patterns and identify regions with similar economic characteristics.

<br>

#### We created box plots to investigate the relationship between primary completion rates (by gender) across GDP per capita ranks. These plots offer insights to spread, medians, and outliers within each rank category. We created scatter plots to examine GDP per capita and education gap, along with GDP per capita and the OOSR (by gender), as all are continuous variables. For these graphs, we filtered out the zero values to prevent distortion in the visualizations.

<br>

#### The primary key used for merging was the "Country.Territory" in the GDP dataset and "Countries.and.areas" in the global education dataset. This approach ensured that the analysis focused on countries for which both economic and educational data were available. To ensure the quality of our analysis, we removed missing values in specific variables critical to our research, such as completion rates and the IMF to help prevent biased or inaccurate results. 

<br>

#### While we used box plots and scatter plots for our statistical visualizations, we have not delved into more complex statistical methods, such as regression analysis, at this stage of our exploration. 

<br>

#### For our trade-offs, we were faced with the decision to remove missing values was made to ensure the completeness and reliability of our analysis. However, this comes with the trade-off of potentially reducing our sample size. While we prioritize data quality, we acknowledge that a smaller sample may limit the generalizability of our findings. Also, we removed zero values in GDP to potentially improve the accuracy of our analysis, but it involves the trade-off of excluding certain countries or observations. This decision reflects our commitment to robust and meaningful results but acknowledges the potential loss of information from countries with zero or missing GDP values. 

<br>

#### The boxplots depicting male and female completion rates across the different GDP per capita ranks (low, mid, high) revealed similar patterns. For both, countries with lower GDP per capita tend to have a broader distribution in completion rates, indicating higher variability. The median completion rate was lower for countries with lower GDP per capita. Additionally, there was a presence of more outliers in high GDP countries, exhibited in both the female and male graphs.

# *add in box plots*

<br>

#### The scatterplot visualizing the relationship between GDP per capita and the unemployment gap showed that in countries with lower GDPs, the unemployment gap tends to be larger. 

# *add in box plots*

<br>

#### The scatterplots visualizing the relationship between GDP per capita and the male and female OSSR showed that in countries with lower GDPs, they tend to have higher OOSRs for both females and males. 

# *add in scatterplots*

<br>

#### The world map offers a geographical visualization on economic disparities and global economic distribution. Countries were visually categorized based on their economic status (GDP per capita). 

# *add map*

<br>

#### The summary table shows the medians of the key indicators across the GDP per capita categories, showing an overview of the economic and educational outcomes. Completion rates for both females and males are positively associated with higher GDP, shown by the higher medians in the High GDP category. The unemployment rate medians show that unemployment rates tend to decrease with rising GDP. The OOSR shows variations between GDP categories. The education gap is notable in low GDP countries, with a higher education gap in low GDP.

# *add table*

<br>

#### Education Gap Across GDP Categories:
#### The education gap, representing the gap in completion rates between males and females, is pronounced in countries with Low GDP. This suggests that economic status may have a gender-specific influence on educational outcomes, suggesting that we need more targeted interventions to address gender disparities in educational access and achievement within economically challenged countries.

<br>

#### Completion Rates/Out-of-School Rates and Economic Prosperity:
#### The completion rates for primary education, both for females and males, exhibit a positive correlation with higher GDP per capita. Countries categorized as "High" GDP demonstrate higher median completion rates, emphasizing the potential impact of economic prosperity on educational success, suggesting that advanced economies may allocate more resources to education, resulting in improved completion rates. In addition, OSSR rates in relation to GDP per capita provide additional depth to the inclusivity and accessibility of a country’s education system.

<br>

#### Unemployment Rates and Economic Prosperity:
#### The inverse relationship observed between unemployment rates and GDP per capita shows that economic prosperity could contribute to employment opportunities, especially since higher GDP countries tend to exhibit lower unemployment rates.

<br>

#### Limitations and Caution in Interpretation:
#### The presence of missing data, particularly in the "NA: Insufficient Data" category, illustrates the challenges of conducting a comprehensive analysis. Thus, we approached our interpretations with caution, recognizing the potential impact of outliers and missing values on the overall narrative.

<br>

#### Future Directions:
#### In the future, we would like to explore the factors contributing to the education gap, especially in lower GDP countries, as it would provide a better understanding of gender-related challenges in education. A closer examination of these disparities could inform targeted strategies for improvement. 

<br>

